import "../styles/globals.css";
import Head from "next/head";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>383 Browser Compatibility</title>
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Nanum+Gothic&family=Pathway+Gothic+One&display=swap"
          rel="stylesheet"></link>
        <meta name="description" content="Generated by Jacques" />
      </Head>
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
